version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "rural-healthcare-assistant"
resolve_s3 = true
s3_prefix = "rural-healthcare-assistant"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=dev"
